# Generated by Django 4.2.7 on 2023-11-21 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('piada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JokeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup', models.TextField(default='Sem Setup')),
                ('delivery', models.TextField(default='Sem delivery')),
                ('liked', models.ManyToManyField(related_name='liked_joke_boards', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
