# Generated by Django 4.2.7 on 2023-11-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piada', '0002_jokeboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jokeboard',
            name='usuario',
            field=models.TextField(default='Anônimo'),
        ),
    ]
